import "jquery";
import "../templates/vendor/jquery.validate/additional-methods";
import "../templates/vendor/jquery.validate/jquery.validate";
import "../templates/vendor/jquery.autoellipsis";
import "../templates/vendor/jquery.contextMenu.min";
import "../templates/vendor/jquery.smartWizard.min";
import "../templates/vendor/jquery.barrating.min";

import "bootstrap";
import "../templates/vendor/Chart.bundle.min.js";

// import "../templates/vendor/datatables.min.js";
// import "../templates/vendor/datatables-bootstrap.js";
import "../templates/dore-plugins/select.from.library";
import "../templates/vendor/bootstrap-datepicker";
import "../templates/vendor/bootstrap-notify.min";
import "../templates/vendor/baguetteBox.min";
import "../templates/vendor/countdown.min";
import "../templates/vendor/cropper.min";
import "../templates/vendor/moment.min.js";
import "../templates/vendor/fullcalendar.min.js";
// import "../templates/vendor/glide.min.js";
import "../templates/vendor/mousetrap.min";
import "../templates/vendor/nouislider.min";
// import "../templates/vendor/owl.carousel.min";
import "../templates/vendor/perfect-scrollbar.min";
import "../templates/vendor/progressbar.min";
import "../templates/vendor/quill.min";
import "../templates/vendor/select2.full";
import "../templates/vendor/slick.min";
import "../templates/vendor/Sortable";
import "../templates/vendor/typeahead.bundle";
import "../templates/vendor/video";
// import "../templates/vendor/videojs-youtube.min";
import "../templates/dore.script";
import "../templates/scripts";
import "../templates/scripts.single.theme.js";
import "../templates/vendor/dropzone.min";

$('.calendar').fullCalendar({ });
