class CreateOrganizationStats < ActiveRecord::Migration[5.2]
  def change
    create_table :organization_stats do |t|
      t.integer :tree_count, default: 0, comment: "The amount of trees planted as a result of transportation assignments"
      t.float :tree_emission_impact, default: 0, comment: "The amount of carbon dioxide generated by the tree count"
      t.float :kilometer_count, default: 0, comment: "The amount of zero-emission kilometers driven with Contaynor"
      t.float :kilometer_emission_impact, default: 0, comment: "The amount of carbon dioxide prevented by driving zero-emission with Contaynor"
      t.references :organization, foreign_key: true

      t.timestamps
    end
  end
end
